### ISSUE TITLE
Crash on Linux (GPU process isn't usable)

### ISSUE THREAD

**Issue by KorbsStudio** [lostdesign/linked#103]
**Describe the bug**
When opening linked, it shows a blank window for a few moments, then crashes.
I choice to open it with the terminal to see if there were any errors, here's what shows up:
```
[103363:1108/154006.596431:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Expected behavior**
Application opens without crashing, and shows content.

**Screenshots**
<video src="https://user-images.githubusercontent.com/51213244/140815673-97db5d99-6b4d-4480-aaae-d2565660ebea.mp4"></video>

**Desktop (please complete the following information):**
 - linked version: 1.3.7
 - operating system: Fedora 35

**Comment by dragonDScript** [comment]
Try disabling hardware acceleration.

**Comment by KorbsStudio** [comment]
After trying `app.disableHardwareAcceleration`, the same error occurs.

**Comment by dragonDScript** [comment]
Have you fixed it? If so, how?
