### ISSUE TITLE
🐛  - Catalan months are wrong

### ISSUE THREAD

**Issue by aitor-gomila** [lostdesign/linked#111]
**Describe the bug**
Catalan months are wrong. They should be "novembre del 2021", and not "de novembre 2021" for example.

**To Reproduce**
1. Pick catalan
2. See error

**Expected behavior**
They should be "novembre del 2021" or "novembre 2021", as all other latin languages.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/46191980/142657992-c30e3163-8b88-49d8-b0c1-57385c4179e0.png)

**Desktop (please complete the following information):**
 - linked version: master branch (not released yet)
 - operating system: all (mine is windows 10 home)

**Comment by lostdesign** [comment]
![img](https://media.discordapp.net/attachments/910936772555448373/911291184561934366/Bildschirmfoto_2021-11-19_um_17.25.40.png?width=2253&height=1631)

It seems to be a luxon issue, as it also does not react properly in isolation while the INTL API, which is used by luxon, works as expected.

**Comment by dragonDScript** [comment]
A quick fix would be to show the current day (e.g. 25th November 2021, 25 de novembre del 2021)

**Comment by lostdesign** [comment]
> A quick fix would be to show the current day (e.g. 25th November 2021, 25 de novembre del 2021)

That won't happen as it does not fit well in the design. I'll rather check luxon itself or drop the translation.

**Comment by dragonDScript** [comment]
> > A quick fix would be to show the current day (e.g. 25th November 2021, 25 de novembre del 2021)
> 
> That won't happen as it does not fit well in the design. I'll rather check luxon itself or drop the translation.

As I told you in the DMs you can use the Intl API to get the month an year and concatenate them, maybe that would work for all languages and fix the design.
