### ISSUE TITLE
✨ add linked to AUR (arch linux repository)

### ISSUE THREAD

**Issue by lostdesign** [lostdesign/linked#132]
See https://wiki.archlinux.org/title/Arch_User_Repository#Submitting_packages

Things to check
- [ ] is auto-updating allowed and possible with pacman?
- [ ] how to publish package via CI

**Comment by redxtech** [comment]
By autoupdating do you mean the app updates itself?

If so, that's not something that is recommended for arch. Everything gets updated when you run the update command, downloading the new version from the AUR/repos.

**Comment by lostdesign** [comment]
@redxtech yeah the app is auto-updating just like it does now. Since it is not **recommended**, would it still work? Or would they deny the request?

**Comment by lostdesign** [comment]
closing in favor of https://github.com/lostdesign/linked/discussions/159
