### ISSUE TITLE
🐛  - Slash command not working properly on clean installations

### ISSUE THREAD

**Issue by CarlosPC94** [lostdesign/linked#184]
**Describe the bug**
When you make a clean installation of the application with development purposes the slash command doesn't shows the popup and the application is useless

**To Reproduce**
1. Make a clean installation of the app and launch to work as a developer
2. Introduce a slash in the editor to show the popup with the avilable options

**Expected behavior**
A pop up appears with all the available options to write in the editor

**Current behavior**
The popup doesn't appear so you can't add anything more than plain text

**Screenshots**
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/61242676/194752630-e736f051-7359-444a-a192-03e2fbaae47d.png">

**Desktop (please complete the following information):**
 - linked version: 1.5.4 beta
 - operating system: Every operating system

**Comment by lostdesign** [comment]
Thanks for fixing the issue!
