### ISSUE TITLE
Language change issue on Settings page

### ISSUE THREAD

**Issue by lostdesign** [lostdesign/linked#204]
### Discussed in https://github.com/lostdesign/linked/discussions/202

<div type='discussions-op-text'>

<sup>Originally posted by **Faisal-Sey** March 30, 2024</sup>
The Beta Test Program text does not change when the language is changed.

![Screenshot 2024-03-30 204448](https://github.com/lostdesign/linked/assets/63804699/f5131f45-ea2b-4720-9ee5-2997b9c35926)
</div>

**Comment by Faisal-Sey** [comment]
@lostdesign can you assign it to me and grant me write access

**Comment by Faisal-Sey** [comment]
@lostdesign we can close the issue now
