### ISSUE TITLE
🐛  - Cant open contributions

### ISSUE THREAD

**Issue by takumade** [lostdesign/linked#74]
https://github.com/lostdesign/linked/blob/master/contributing.md

Is giving me 404

**Comment by lostdesign** [comment]
Oh wow, github is case sensitive, TIL? https://github.com/lostdesign/linked/blob/master/CONTRIBUTING.md
Going to fix, thanks

**Comment by takumade** [comment]
Ok thanks

**Comment by lostdesign** [comment]
Fixed it!
