### ISSUE TITLE
🐛  - Language Dropdown in Settings is missing

### ISSUE THREAD

**Issue by kriskbx** [lostdesign/linked#76]
**Describe the bug**
The language dropdown is missing.

**To Reproduce**
1. Go to Settings

**Expected behavior**
It should be there.

**Screenshots**
<img width="562" alt="grafik" src="https://user-images.githubusercontent.com/3148865/126609680-1dcd11ba-26b6-4794-82e0-950e23081b08.png">

**Desktop (please complete the following information):**
 - linked version: 1.3.2
 - operating system macOS Big Sur 11.4

**Additional context**
Probably related to the switch of language codes. Maybe you need to write a migration for older settings?

**Comment by lostdesign** [comment]
Should be fixed in v1.3.4
