### ISSUE TITLE
🐛  - week number breaks on small widths and looks funny

### ISSUE THREAD

**Issue by kriskbx** [lostdesign/linked#87]
**Describe the bug**
Only cosmetic, see screenshot.

**To Reproduce**
1. Make the window as thin as possible

**Expected behavior**
It doesn't break.

**Screenshots**
<img width="562" alt="Screenshot 2021-09-09 at 10 17 51" src="https://user-images.githubusercontent.com/3148865/132649668-26139bf1-2a7b-4f26-bd55-956c5c3eff5e.png">

**Desktop (please complete the following information):**
 - linked version: 1.3.4
 - operating system: macOS 11.5.2

**Comment by lostdesign** [comment]
1.4.0 will have a slightly smaller heading and I am going to handle these things better, maybe even wrap the date/week changer. Different languages cause this effect as well, since certain months can be quite long in different languages :D

**Comment by Mohammadsaead69** [comment]
I am take a mistake.i was want to take the private repository

**Comment by Mohammadsaead69** [comment]
And mistakes publiced

**Comment by Mohammadsaead69** [comment]
What I do??????
