### ISSUE TITLE
🐛 Dependency error after initial package install on serving - fs.existsSync is not a function

### ISSUE THREAD

**Issue by richardevcom** [lostdesign/linked#94]
**Describe the bug**
Getting `fs.existsSync is not a function` after initial setup via `yarn`.

**To Reproduce**
1. Clone repository
2. Run `yarn` to setup dependecies
3. Run `yarn serve`
4. Get whitescreen and see error in console

**Expected behavior**
Run app without an error.

**Desktop (please complete the following information):**
 - linked version: 1.3.5
 - operating system  Microsoft Windows 10 Home, 10.0.19043 N/A Build 19043

**Additional context**
Some people mention that this issue may be due to Visual Code IDE automatically add in dependecies, but I can't demonstrate that it is the same case here.

**Comment by richardevcom** [comment]
Nevermind. It happens on older node.js (v14 for example). Upgrade fixed the issue. Closing issue.

**Comment by lostdesign** [comment]
1) About the steps you did:

> Clone repository
> Run yarn to setup dependecies
> Run yarn serve
> Get whitescreen and see error in console

This is not the right way to build/serve the app. The right command is `yarn electron:serve` as per readme https://github.com/lostdesign/linked#contributing

2) Unsure what you mean by missing dependencies? If the right node version (readme, tldr: atleast node 16) is used, the project will start and build just fine.

**Comment by richardevcom** [comment]
Yes. I understood it after I tried rebuild build everything (so I closed the issue since It was my fault).
But the v16 of node.js fixed most dependecy issues. and the rest steps + `yarn build:all` fixed visual errors as well.
